### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_hash'

### ISSUE THREAD

**Issue by Nytyr** [spesmilo/electrum-server#148]
I'm getting this error while starting the server:

INFO:electrum:Starting Electrum server on localhost
Traceback (most recent call last):
  File "/usr/local/bin/run_electrum_server.py", line 5, in <module>
    pkg_resources.run_script('electrum-server==1.0', 'run_electrum_server.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/electrum_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_server.py", line 318, in <module>

  File "/usr/local/lib/python2.7/dist-packages/electrum_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_server.py", line 257, in start_server

  File "build/bdist.linux-x86_64/egg/electrumserver/blockchain_processor.py", line 55, in **init**
  File "build/bdist.linux-x86_64/egg/electrumserver/storage.py", line 211, in **init**
AttributeError: 'NoneType' object has no attribute 'get_hash'

Thanks

**Comment by ecdsa** [comment]
I guess you started electrum-server with an incomplete database.
