### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by webdawg** [spesmilo/electrum-server#154]
Trying to get my electrum server synced and it keeps stopping with this error:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/electrumserver/blockchain_processor.py", line 104, in do_catch_up
    self.catch_up(sync=False)
  File "/usr/lib/python2.7/site-packages/electrumserver/blockchain_processor.py", line 709, in catch_up
    self.print_time(n)
  File "/usr/lib/python2.7/site-packages/electrumserver/blockchain_processor.py", line 128, in print_time
    tx_per_second = (1-alpha2) * tx_per_second + alpha2 * num_tx / delta
ZeroDivisionError: float division by zero

^CINFO:electrum:Stopping Stratum

I assume delta becomes zero at a point.  Any ideas?

**Comment by webdawg** [comment]
I see that it is part of some reporting, at the moment I am going to try this:

delta = time.time() - self.time_ref + 0000000000.000001

**Comment by webdawg** [comment]
So far so good...running for 6 hrs.

**Comment by webdawg** [comment]
Running for days.  Anyone think this could have something to do with this:  http://xenbits.xen.org/docs/4.3-testing/misc/tscmode.txt

**Comment by webdawg** [comment]
#155 proposed
