### ISSUE TITLE
Sometimes electrum-server fails to start when not fully synced with bitcoind

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum-server#172]
After several reboots for applying updates electrum-server refused to start with bitcoind and catch up on the blockchain. Here is the traceback:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/electrumserver/blockchain_processor.py", line 104, in do_catch_up
    self.header = self.block2header(self.bitcoind('getblock', (self.storage.last_hash,)))
  File "build/bdist.linux-x86_64/egg/electrumserver/blockchain_processor.py", line 171, in bitcoind
    raise BaseException(r['error'])
BaseException: {u'message': u'Block not found', u'code': -5}

**Comment by EagleTM** [comment]
It basically means bitcoind is not synced up yet and you should wait for that to happen. I was under the impression we're catching "Block not found" with a better error message like "bitcoind probably not synced up yet" but looks like that's not the case.

**Comment by gits7r** [comment]
Yes but almost every time when bitcoind is not synced up electrum returns: Bitcoind still warming up while keeps running and waits for bitcoind to warm up... while in this particular case described here (which happens rare which is true) electrum-server dies with the stack trace above.
