### ISSUE TITLE
electrum-server start problem

### ISSUE THREAD

**Issue by freshonline** [spesmilo/electrum-server#180]
/etc/electrum.conf:
=======================
[bitcoind]
bitcoind_host = localhost
bitcoind_port = 8332
# user and password from bitcoin.conf (not needed for localhost)
# bitcoind_user =
# bitcoind_password =
=====================
electrum.log:
=========================

ConfigParser.NoOptionError: No option 'bitcoind_user' in section: 'bitcoind'
==============================
electrum-server start localhost.
bitcoind_user don't have password.
==================================
[bitcoind]
bitcoind_host = localhost
bitcoind_port = 8332
# user and password from bitcoin.conf (not needed for localhost)
bitcoind_user =
bitcoind_password =
===========================
or
=========================
[bitcoind]
bitcoind_host = localhost
bitcoind_port = 8332
# user and password from bitcoin.conf (not needed for localhost)
bitcoind_user = bitcoin
bitcoind_password = pass
===========================
root@serv:~# electrum-server start
Starting server as daemon
root@serv:~# electrum-server status
Server not running
root@serv:~# cat /var/log/electrum.log
Starting Electrum server on localhost
db init
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/electrumserver/storage.py", line 205, in __init__
    self.db_utxo = DB(self.dbpath, 'utxo', config.getint('leveldb', 'utxo_cache'))
  File "build/bdist.linux-x86_64/egg/electrumserver/storage.py", line 154, in __init__
    self.db = plyvel.DB(os.path.join(path, name), create_if_missing=True, compression=None, lru_cache_size=cache_size)
  File "_plyvel.pyx", line 236, in plyvel._plyvel.DB.__init__ (plyvel/_plyvel.cpp:3129)
  File "_plyvel.pyx", line 80, in plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1698)
IOError: IO error: lock /var/electrum-server/utxo/LOCK: Resource temporarily unavailable
Stopping Stratum
Initializing database
Traceback (most recent call last):
  File "/usr/local/bin/run_electrum_server.py", line 4, in <module>
    __import__('pkg_resources').run_script('electrum-server==1.0', 'run_electrum_server.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/electrum_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_server.py", line 307, in <module>

  File "/usr/local/lib/python2.7/dist-packages/electrum_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_server.py", line 254, in start_server

  File "build/bdist.linux-x86_64/egg/electrumserver/blockchain_processor.py", line 80, in __init__
  File "build/bdist.linux-x86_64/egg/electrumserver/storage.py", line 220, in __init__
  File "build/bdist.linux-x86_64/egg/electrumserver/storage.py", line 355, in put_node
AttributeError: 'Storage' object has no attribute 'db_utxo'
cannot reach bitcoind...
cannot reach bitcoind...
cannot reach bitcoind...
cannot reach bitcoind...
cannot reach bitcoind...
cannot reach bitcoind...

**Comment by Vertux** [comment]
I got the same problem.
