### ISSUE TITLE
irc: disconnected

### ISSUE THREAD

**Issue by DigitalCoin1** [spesmilo/electrum-server#192]
I am creating a private server for my currency and am getting this error.

The connection to my Coinomi wallet happens (or at least shows my IP in Electrum debug), but there is no update in the app.

```
[02/11/2019-23:59:40] irc: disconnected
[02/11/2019-23:59:40] irc
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/electrumserver/ircthread.py", line 172, in run
    client.process_forever()
  File "build/bdist.linux-x86_64/egg/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "build/bdist.linux-x86_64/egg/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "build/bdist.linux-x86_64/egg/irc/client.py", line 216, in process_data
    c.process_data()
  File "build/bdist.linux-x86_64/egg/irc/client.py", line 573, in process_data
    self.disconnect("Connection reset by peer")
  File "build/bdist.linux-x86_64/egg/irc/client.py", line 779, in disconnect
    self._handle_event(Event("disconnect", self.server, "", [message]))
  File "build/bdist.linux-x86_64/egg/irc/client.py", line 673, in _handle_event
    self.reactor._handle_event(self, event)
  File "build/bdist.linux-x86_64/egg/irc/client.py", line 398, in _handle_event
    result = handler.callback(connection, event)
  File "build/bdist.linux-x86_64/egg/electrumserver/ircthread.py", line 107, in on_disconnect
    raise BaseException("disconnected")
BaseException: disconnected
[02/11/2019-23:59:40] ERROR: cannot parse 56a619a4f56b47592bfe5258b49c7b8e0e92afb14fba3f303555d29c363f5995
[02/11/2019-23:59:40] block 389986 (0 0.04s) 9c293dce39703da3bd4b90e225568be5a81fef9278f689120f3b8c2552b01dc5 (0.00tx/s, 0.90s/block)
[02/11/2019-23:58:08] cannot start TCP session[Errno 2] No such file or directory ('MYIP', 49618)
[02/11/2019-23:58:18] TCP   MYIP:44956   26 unknown

```

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum-server#note
> This code is now unmaintained. The replacement code for electrum server is ElectrumX: https://github.com/kyuupichan/electrumx
