### ISSUE TITLE
Electrum server not working - log report

### ISSUE THREAD

**Issue by viperperidot** [spesmilo/electrum-server#196]
I had my Electrum Server working for many months and just recently it stopped working (the only change I made recently was upgrading my wallets to the latest Electrum). I notice that it keeps going back to 99.9% synced status and when my wallets try to connect it looks like it tries to connect for a split second and then loses connection. Not sure what is wrong but here is my log file, one thing it note is I do have it running on myNode. If this would be better to post on their Git please let me know. Thanks

Nov 20 11:12:15 myNode electrs[10196]: thread 'acceptor' panicked at 'accept failed: Os { code: 24, kind: Other, message: "Too many open files" }', src/rpc.rs:533:38
Nov 20 11:09:18 myNode electrs[10196]: 2020-11-20T11:09:18.505-06:00 - WARN - failed to export process stats: failed to read /proc/self/stat
Nov 20 11:06:07 myNode electrs[10196]: 2020-11-20T11:06:07.322-06:00 - INFO - [127.0.0.1:42222] disconnected peer
Nov 20 11:06:07 myNode electrs[10196]: 2020-11-20T11:06:07.321-06:00 - DEBUG - [127.0.0.1:42222] shutting down connection
Nov 20 11:06:07 myNode electrs[10196]: 2020-11-20T11:06:07.321-06:00 - TRACE - RPC Done
Nov 20 11:06:07 myNode electrs[10196]: 2020-11-20T11:06:07.321-06:00 - TRACE - closing 477 RPC connections
Nov 20 11:06:07 myNode electrs[10196]: 2020-11-20T11:06:07.319-06:00 - TRACE - stop accepting new RPCs
Nov 20 11:06:05 myNode electrs[10196]: thread 'peer' panicked at 'failed to clone TcpStream: Os { code: 24, kind: Other, message: "Too many open files" }', src/rpc.rs:452:37
Nov 20 11:06:05 myNode electrs[10196]: 2020-11-20T11:06:05.418-06:00 - INFO - [127.0.0.1:50328] connected peer
Nov 20 11:06:05 myNode electrs[10196]: 2020-11-20T11:06:05.417-06:00 - TRACE - [127.0.0.1:50328] spawned ThreadId(1355)
Nov 20 11:05:54 myNode electrs[10196]: thread 'peer' panicked at 'failed to clone TcpStream: Os { code: 24, kind: Other, message: "Too many open files" }', src/rpc.rs:452:37
Nov 20 11:05:54 myNode electrs[10196]: 2020-11-20T11:05:54.882-06:00 - INFO - [127.0.0.1:50308] connected peer
Nov 20 11:05:54 myNode electrs[10196]: 2020-11-20T11:05:54.882-06:00 - TRACE - [127.0.0.1:50308] spawned ThreadId(1354)
Nov 20 11:05:52 myNode electrs[10196]: 2020-11-20T11:05:52.312-06:00 - TRACE - RPC PeriodicUpdate
Nov 20 11:05:44 myNode electrs[10196]: thread 'peer' panicked at 'failed to clone TcpStream: Os { code: 24, kind: Other, message: "Too many open files" }', src/rpc.rs:452:37
Nov 20 11:05:44 myNode electrs[10196]: 2020-11-20T11:05:44.152-06:00 - INFO - [127.0.0.1:50300] connected peer
Nov 20 11:05:44 myNode electrs[10196]: 2020-11-20T11:05:44.152-06:00 - TRACE - [127.0.0.1:50300] spawned ThreadId(1353)
Nov 20 11:05:36 myNode electrs[10196]: 2020-11-20T11:05:36.848-06:00 - TRACE - RPC PeriodicUpdate

**Comment by viperperidot** [comment]
Didn't realize this repo is innactive
